# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yusuke Tsutsumi
email: "email: y at tsutsumi dot io"
description: >- # this means to ignore newlines until "baseurl:"
  My blog on software, productivity, and obsessively optimizing. I work at
  Google, ex-Zillow. Thoughts my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://y.tsutsumi.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tsutsumiyusuke
github_username: toumorokoshi
permalink: /:year/:month/:day/:slug/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-diagrams
  - jekyll-analytics
  - jekyll-redirect-from
feed:
  path: feed/index.xml
# Disqus is ad-supported and includes telemetry, so
# only load it if people opt-in.
disqus:
  shortname: tsutsumi

google_analytics: G-325KP61WS9

header_pages:
  - pages/resources.md
  - pages/about.md

minima:
  social_links:
    twitter: tsutsumiyusuke
    github: toumorokoshi
    linkedin: yusuke-tsutsumi

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
