def main(build):
    build.packages.install("aiohttp")
    build.packages.install("attrs")
    build.packages.install("async-timeout")
    build.packages.install("flask")
    build.packages.install("jupyter")
    build.packages.install("matplotlib")
    build.packages.install("marshmallow")
    build.packages.install("plotly")
    build.packages.install("schematics")
