name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */10 * * *'  # every day at midnight

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: download blog posts from Dropbox
        run: ./scripts/download-blog-from-dropbox.sh
        env:
          DROPBOX_ACCESS_TOKEN: ${{secrets.DROPBOX_ACCESS_TOKEN}}
      - uses: helaili/jekyll-action@2.0.3
        env:
          JEKYLL_PAT: ${{secrets.JEKYLL_PAT}}