name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: download-blog-posts-from-dropbox
        run: ./scripts/download-blog-from-dropbox.sh
        env:
          DROPBOX_ACCESS_TOKEN: ${{secrets.DROPBOX_ACCESS_TOKEN}}
      - name: install-deps
        run: sudo apt install -y npm && npm install -g mermaid.cli
      - name: build-site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # JEKYLL_PAT: ${{secrets.JEKYLL_PAT}}