name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: install-deps
        run: |
          sudo apt install -y npm
          npm install -g @mermaid-js/mermaid.cli
          pip install google-api-python-client
          pip install google-auth
      - name: build-site
        run: ./scripts/build.sh
        env:
          BLOG_FOLDER_ID: ${{ secrets.BLOG_FOLDER_ID }}
          BLOG_CRED_FILE_CONTENT: ${{ secrets.BLOG_CRED_FILE_CONTENT }}
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # JEKYLL_PAT: ${{secrets.JEKYLL_PAT}}