name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - feature/jekyll

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{secrets.GITHUB_TOKEN}}